# Generated by Django 4.0.5 on 2022-07-01 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('code', models.CharField(max_length=5, verbose_name='Code')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Value')),
                ('value_date', models.DateTimeField(verbose_name='Value Date')),
                ('nominal', models.IntegerField(default=1, verbose_name='Nominal')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_currency', to='currencies.currency', verbose_name='Currency')),
            ],
            options={
                'ordering': ('-value_date',),
            },
        ),
    ]
