# Generated by Django 4.0.5 on 2022-07-01 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'currency', 'verbose_name_plural': 'currencies'},
        ),
        migrations.AlterModelOptions(
            name='currencyrate',
            options={'ordering': ('-value_date',), 'verbose_name': 'currency rate', 'verbose_name_plural': 'currency rates'},
        ),
    ]
