# Generated by Django 4.0.5 on 2022-07-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_alter_currency_options_alter_currencyrate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyrate',
            name='hash',
            field=models.CharField(default=None, max_length=64, null=True, unique=True),
        ),
    ]
